apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-react
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: frontend-react
    weight: 100
  wildcardPolicy: None
